### ISSUE TITLE
Changing permissions not permitted

### ISSUE THREAD

**Issue by atournayre** [php-actions/phpstan#22]
I'm having an issue running the CI and here is the log.

```
Run php-actions/phpstan@v3
  with:
    path: src
    configuration: tools/phpstan/phpstsan.neon
    version: composer
    php_version: latest
    command: analyse
Run set -e
  set -e
  bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/59e915e4b8eeab830231a5dce6ad0998adebac05/php-build.bash) phpstan
  /home/runner/work/_actions/php-actions/phpstan/v3/phpstan-action.bash
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ACTION_TOKEN: ***
    ACTION_VERSION: composer
    ACTION_PHP_VERSION: latest
    ACTION_PHPSTAN_PATH: 
    ACTION_PHP_EXTENSIONS: 
    ACTION_COMMAND: analyse
    ACTION_PATH: src
    ACTION_CONFIGURATION: tools/phpstan/phpstsan.neon
    ACTION_LEVEL: 
    ACTION_PATHS_FILE: 
    ACTION_AUTOLOAD_FILE: 
    ACTION_ERROR_FORMAT: 
    ACTION_GENERATE_BASELINE: 
    ACTION_MEMORY_LIMIT: 
    ACTION_ARGS: 
Building PHP latest with extensions:  ...
chmod: changing permissions of '/home/runner/work/[PROJECT]/[PROJECT]/vendor/bin/phpstan': Operation not permitted
Error: Process completed with exit code 1.
```

CI was working well 3 days ago and today this issue. No change to the CI configuration of the project were made.

It seems that some new commits appends to this repos, maybe it could be related.

**Comment by g105b** [comment]
Hi, thank you for bringing this to my attention. You are right that the latest updates are probably to blame for this. Because of this, I will do some more rigorous testing and update soon. 

In the meantime, a solution is to use a fixed version number for your action:

`php-actions/phpstan@v3.0.2` will keep you clamped to the previous version. Using `@v3` will receive updates. I test updates that are made to the `v3` rolling release to try and avoid any knock-on effects like this, but it seems the latest update has introduced some backwards incompatible changes.

I will look into this, document accordingly, and possibly supply a revert commit to `v3` and release `v4` instead, if the changes can not be free from backwards breaking changes.

**Comment by atournayre** [comment]
Thanks for your answer @g105b !

Fixing the version works like a charm.

Will you close this issue when it will be fixed or do I close it?

**Comment by g105b** [comment]
I'll close this issue once I've worked on and tested a solution. I'll keep you updated via this thread.

**Comment by ozahorulia** [comment]
I'm getting the same problem on v3.0.2:

Building PHP 8.1 with extensions: redis ...
chmod: changing permissions of '/home/runner/work/<REPO>/vendor/bin/phpstan': Operation not permitted
